// supabase/vue-supabase/src/components/AppLayout.vue
<template>
  <Navbar />
  <div class="divider"></div>

  <div class="text-center my-3">
    <ConditionFilter @searchUser="(value) => (queryName = value)" />

    <Table :displayUsers="displayUsers" />
  </div>

  <Footer />
</template>

<script setup>
import { ref, onMounted, computed } from "vue";
import { faker } from "@faker-js/faker";

import Table from "./Table.vue";
import ConditionFilter from "./ConditionFilter.vue";
import Footer from "./Footer.vue";
import Navbar from "./Navbar.vue";

const queryName = ref("");
const users = ref([]);

const displayUsers = computed(() => {
  if (queryName.value.length === 0) {
    return users.value;
  }

  return users.value.filter((user) => user.name.includes(queryName.value));
});

onMounted(() => {
  const usersArr = Array.from({ length: 10 }, (_, idx) => ({
    id: idx,
    avatar: faker.image.avatar(),
    name: faker.internet.userName(),
    country: faker.location.country(),
    company: faker.company.buzzPhrase(),
    role: faker.person.jobTitle(),
  }));

  users.value = usersArr;
});
</script>

// supabase/react-supabase/src/components/AppLayout.jsx
import Footer from "./Footer";
import Navbar from "./Navbar";
import ConditionFilter from "./ConditionFilter";
import Table from "./Table";
import { useEffect, useState } from "react";
import { faker } from "@faker-js/faker";

const AppLayout = () => {
  const [queryName, setQueryName] = useState("");
  const [users, setUsers] = useState([]);

  const displayUsers = queryName
    ? users.filter((user) => user.name.includes(queryName))
    : users;

  useEffect(() => {
    const usersArr = Array.from({ length: 10 }, (_, idx) => ({
      id: idx,
      avatar: faker.image.avatar(),
      name: faker.internet.userName(),
      country: faker.location.country(),
      company: faker.company.buzzPhrase(),
      role: faker.person.jobTitle(),
    }));

    setUsers(usersArr);
  }, []);

  return (
    <>
      <Navbar />
      <div className="divider"></div>

      <div className="text-center my-3">
        <ConditionFilter onSearch={(value) => setQueryName(value)} />
        <Table displayUsers={displayUsers} />
      </div>

      <Footer />
    </>
  );
};
export default AppLayout;
