// supabase/vue-supabase/src/components/Table.vue
<template>
  <div class="overflow-x-auto">
    <table class="table">
      <thead>
        <tr>
          <th>
            <label>
              <input type="checkbox" class="checkbox" />
            </label>
          </th>
          <th>Name</th>
          <th>Job</th>
          <th>Operation</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="user in displayUsers">
          <th>
            <label>
              <input type="checkbox" class="checkbox" />
            </label>
          </th>
          <td>
            <div class="flex items-center gap-3">
              <div class="avatar">
                <div class="mask mask-squircle w-12 h-12">
                  <img :src="user.avatar" alt="Avatar Tailwind CSS Component" />
                </div>
              </div>
              <div>
                <div class="font-bold">{{ user.name }}</div>
                <div class="text-sm opacity-50">{{ user.country }}</div>
              </div>
            </div>
          </td>
          <td>
            {{ user.company }}
            <br />
            <span class="badge badge-ghost badge-sm">{{ user.role }}</span>
          </td>
          <th>
            <button class="btn btn-ghost btn-xs">Edit</button>
            <button class="btn btn-outline btn-error btn-xs">Delete</button>
          </th>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup>
const props = defineProps({
  displayUsers: {
    type: Array,
    default: () => [],
    required: true,
  },
});
</script>

// supabase/react-supabase/src/components/Table.jsx
const Table = ({ displayUsers }) => {
  return (
    <div className="overflow-x-auto">
      <table className="table">
        <thead>
          <tr>
            <th>
              <label>
                <input type="checkbox" className="checkbox" />
              </label>
            </th>
            <th>Name</th>
            <th>Job</th>
            <th>Operation</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {displayUsers.map((user) => (
            <tr key={user.id}>
              <th>
                <label>
                  <input type="checkbox" className="checkbox" />
                </label>
              </th>
              <td>
                <div className="flex items-center gap-3">
                  <div className="avatar">
                    <div className="mask mask-squircle w-12 h-12">
                      <img
                        src={user.avatar}
                        alt="Avatar Tailwind CSS Component"
                      />
                    </div>
                  </div>
                  <div>
                    <div className="font-bold">{user.name}</div>
                    <div className="text-sm opacity-50">{user.country}</div>
                  </div>
                </div>
              </td>
              <td>
                {user.company}
                <br />
                <span className="badge badge-ghost badge-sm">{user.role}</span>
              </td>
              <th>
                <button className="btn btn-ghost btn-xs">Edit</button>
                <button className="btn btn-outline btn-error btn-xs">
                  Delete
                </button>
              </th>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};
export default Table;
