// supabase/react-supabase/src/components/ConditionFilter.jsx
import { useEffect, useState } from "react";

const ConditionFilter = ({ onSearch }) => {
  const [queryName, setQueryName] = useState("");

  useEffect(() => {
    onSearch(queryName);
  }, [queryName]);

  return (
    <div>
      <input
        type="text"
        placeholder="username"
        className="input input-bordered w-full max-w-xs"
        onChange={(event) => setQueryName(event.target.value)}
      />
    </div>
  );
};
export default ConditionFilter;

// supabase/vue-supabase/src/components/ConditionFilter.vue
<template>
  <div>
    <input
      type="text"
      placeholder="username"
      class="input input-bordered w-full max-w-xs"
      v-model="queryName"
    />
  </div>
</template>

<script setup>
import { ref, watch } from "vue";

const emits = defineEmits(["search-user"]);
const queryName = ref("");
const searchUser = () => {
  emits("search-user", queryName.value);
};

watch(queryName, () => {
  searchUser();
});
</script>
